Watching for file changes with StatReloader
books not found when generating links
Usuario creado: Personal003 Policial003
Internal Server Error: /admin/home/usuario/add/
Traceback (most recent call last):
  File "C:\CVPL2\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\CVPL2\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\CVPL2\env\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "C:\CVPL2\env\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\CVPL2\env\lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "C:\CVPL2\django-material-kit\home\admin.py", line 138, in custom_add_view
    logger.info('Tecnico creado: %s', tecnico)
UnboundLocalError: local variable 'tecnico' referenced before assignment
C:\CVPL2\django-material-kit\home\admin.py changed, reloading.
Watching for file changes with StatReloader
books not found when generating links
Usuario creado: Personal004 Policial004
Personal policial creado: Personal004 Policial004
books not found when generating links
